version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
      timeout: 30s
    restart: always

  airflow-webserver:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3}
    command: webserver
    ports:
      - 8080:8080
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=
      - AIRFLOW__CORE__ENCRYPT_S3_LOGS=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=any-random-string
      - AIRFLOW__CORE__SECURE_MODE=false
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - PINECONE_API_KEY=${PINECONE_API_KEY:-pcsk_7S6Ri9_JgJjwFETVt5hbMPbPkzprMmyFuKU8cJZcawVRWpajBDwkmxF8A8m5mvAzkeSFoc}
      - PINECONE_ENV=${PINECONE_ENV:-gcp-starter}
      - MODEL_PATH=${MODEL_PATH:-sentence-transformers/all-MiniLM-L6-v2}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - airflow-init
      - postgres

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3}
    command: scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=
      - AIRFLOW__CORE__ENCRYPT_S3_LOGS=false
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      - PINECONE_API_KEY=${PINECONE_API_KEY:-pcsk_7S6Ri9_JgJjwFETVt5hbMPbPkzprMmyFuKU8cJZcawVRWpajBDwkmxF8A8m5mvAzkeSFoc}
      - PINECONE_ENV=${PINECONE_ENV:-gcp-starter}
      - MODEL_PATH=${MODEL_PATH:-sentence-transformers/all-MiniLM-L6-v2}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    restart: always
    depends_on:
      - airflow-init
      - postgres

  airflow-init:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3}
    entrypoint: /bin/bash
    user: "0:0"
    command:
      - -c
      - /opt/airflow/init.sh
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=
      - AIRFLOW__CORE__ENCRYPT_S3_LOGS=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=any-random-string
      - AIRFLOW__CORE__SECURE_MODE=false
    volumes:
      - ./init.sh:/opt/airflow/init.sh
      - ./logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-db-volume: